config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, path: '/owners', controllers: { sessions: 'owners/sessions' }
  devise_for :users, path: '/users', controllers: { sessions: 'users/sessions' }

  root 'apartments#index'

  get '/apartments/list', to: 'apartments#list', as: 'list'
  get '/payment', to: 'payments#index', as: 'payment'
  get '/payment/history', to: 'payments#history', as: 'payment_history'
  post '/apartments/payment', to: 'payments#new_payment', as: 'new_payment'
  get '/apartments/my_apartment', to: 'apartments#my_apartment', as: 'my_apartment'
  get '/apartments/:id/owner_details', to: 'apartments#owner_details', as: 'owner_details'
  post '/apartments/:id/owner_details', to: 'payments#reduce_credit', as: 'reduce_credit'
  post '/apartments/:id', to: 'wishlist#add', as: 'add'

  resources :wishlist

  resources :apartments do
    get 'page/:page', action: :index, on: :collection
  end

  match "/404", to: "errors#not_found",via: :all
  match "/500", to: "errors#internal_server_error",via: :all
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
    unless authenticated_user_or_owner?
      redirect_to user_session_path
    end
  end

  def payment
    if user_signed_in?
      @user = current_user.id
    elsif owner_signed_in?
      @owner = current_owner.id
    else
      redirect_to user_session_path
    end
    new_payment()
  end

  def new_payment

    if authenticated_user_or_owner?
      @credits = user_signed_in? ? User.find(current_user.id) : Owner.find(current_owner.id)
    else
      redirect_to user_session_path
    end
    @credits.credits += 10
    if @credits.save and payment_history("Created Payment for Adding Credits","Credit Card",true)
      redirect_to apartments_path
    else
      redirect_to payment_path
    end
  end

  def history
    if authenticated_user_or_owner?
      @credits = user_signed_in? ? User.find(current_user.id) : Owner.find(current_owner.id)
      @payment_history = user_signed_in? ?
        PaymentHistory.filter_history_by_user_id(current_user.id) :
        PaymentHistory.filter_history_by_owner_id(current_owner.id)
    else
      redirect_to user_session_path
    end
  end
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/history.html.erb
<div class="wrapper rounded">
  <nav class="navbar navbar-expand-lg navbar-dark dark d-lg-flex align-items-lg-start"> <a class="navbar-brand"
            href="#">Transactions
      <p class="text-muted pl-1">Welcome to your transactions</p>
 </a> <button
            class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span
                class="navbar-toggler-icon"></span> </button>
  </nav>
  <div class="row mt-2 pt-2">
    <div class="col-md-6" id="income">
      <div class="d-flex justify-content-start align-items-center">
        <p class="fa fa-certificate"></p>
        <p class="text mx-3">Credits Available</p>
        <p class="text-white ml-4 money"><%= @credits.credits %></p>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-between align-items-center mt-3">
    <ul class="nav nav-tabs w-75">
      <li class="nav-item"> <a class="nav-link active" href="#history">History</a> </li>
      <li class="nav-item"> <a class="nav-link" href="#">Reports</a> </li>
    </ul>
    <%= link_to "Buy Credits", payment_path, :class=>"btn btn-primary"%>
  </div>
  <div class="table-responsive mt-3">
    <table class="table table-dark table-borderless">
      <thead>
        <tr>
          <th scope="col">Activity</th>
          <th scope="col">Mode</th>
          <th scope="col">Date</th>
          <th scope="col" class="text-right">Amount</th>
        </tr>
      </thead>
      <tbody>
        <% @payment_history.each do |p| %>
          <tr>
            <td scope="row"> <span class="fa fa-exchange mr-1"></span> <%= p.message %> </td>
            <% if p.credits_increment %>
              <td><span class="fa fa-cc-mastercard"></span></td>
              <td class="text-muted"><%= (p.created_at).strftime("%d %b %Y %r") %></td>
              <td class="d-flex justify-content-end align-items-center"> <span
                            class="fa fa-long-arrow-up mr-1"></span> +<%= p.credits_increment %> </td>
            <% else %>
              <td><span class="fa fa-coins"></span></td>
              <td class="text-muted"><%= (p.created_at).strftime("%d %b %Y %r") %></td>
              <td class="d-flex justify-content-end align-items-center"> <span
                            class="fa fa-long-arrow-down mr-1"></span> -<%= p.credits_decrement %> </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="d-flex justify-content-between align-items-center results"> <span class="pl-md-3">Showing<b
                class="text-white"> 1-7 0f 200 </b> trasactions</span>
    <div class="pt-3">
      <nav aria-label="Page navigation example">
        <ul class="paginate">
          <li class="page-item disabled"> <a class="page-link" href="#" aria-label="Previous"> <span
                                aria-hidden="true">&lt;</span> </a> </li>
          <li class="page-item"> <a class="page-link" href="#" aria-label="Next"> <span
                                aria-hidden="true">&gt;</span> </a> </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/payments/index.html.erb
<div class="container d-flex justify-content-center mt-5 mb-5">
  <div class="row g-3">
    <div class="col-md-6">
      <span>Payment Method</span>
      <div class="card">
        <div class="accordion" id="accordionExample">
          <div class="card">
            <div class="card-header p-0" id="headingTwo">
              <h2 class="mb-0">
                <button class="btn btn-light btn-block text-left collapsed p-3 rounded-0 border-bottom-custom" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  <div class="d-flex align-items-center justify-content-between">
                    <span>Paypal</span>
                    <i class="fa fa-paypal" style="font-size:2em;"></i>
                  </div>
                </button>
              </h2>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
              <div class="card-body">
                <span class="font-weight-normal card-text">Paypal Email</span>
                <div class="input">
                  <i class="fa fa-paypal"></i>
                </div>
                <input type="text" class="form-control" placeholder="Paypal Email">
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-header p-0">
              <h2 class="mb-0">
                <button class="btn btn-light btn-block text-left collapsed p-3 rounded-0 border-bottom-custom" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                  <div class="d-flex align-items-center justify-content-between">
                    <span>UPI</span>
                    <i class="fa fa-google" style="font-size:1.7em;"></i>
                  </div>
                </button>
              </h2>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
              <div class="card-body">
                <span class="font-weight-normal card-text">UPI ID</span>
                <div class="input">
                  <i class="fa fa-google"></i>
                </div>
                <input type="text" class="form-control" placeholder="UPI ID">
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-header p-0">
              <h2 class="mb-0">
                <button class="btn btn-light btn-block text-left p-3 rounded-0" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  <div class="d-flex align-items-center justify-content-between">
                    <span>Credit card / Debit Card</span>
                    <div class="icons">
                      <i class="fa fa-cc-mastercard" style="font-size:1em;"></i>
                      <i class="fa fa-cc-visa" style="font-size:1em;"></i>
                      <i class="fa fa-cc-stripe" style="font-size:1em;"></i>
                    </div>
                  </div>
                </button>
              </h2>
            </div>
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
              <div class="card-body payment-card-body">
                <span class="font-weight-normal card-text">Card Number</span>
                <div class="input">
                  <i class="fa fa-credit-card"></i>
                  <input type="text" class="form-control" placeholder="0000 0000 0000 0000">
                </div>
                <div class="row mt-3 mb-3">
                  <div class="col-md-6">
                    <span class="font-weight-normal card-text">Expiry Date</span>
                    <div class="input">
                      <i class="fa fa-calendar"></i>
                      <input type="text" class="form-control" placeholder="MM/YY">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <span class="font-weight-normal card-text">CVC/CVV</span>
                    <div class="input">
                      <i class="fa fa-lock"></i>
                      <input type="text" class="form-control" placeholder="000">
                    </div>
                  </div>
                </div>
                <span class="text-muted certificate-text"><i class="fa fa-lock"></i> Your transaction is secured with ssl certificate</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <span>Summary</span>
      <div class="card">
        <div class="d-flex justify-content-between p-3">
          <div class="d-flex flex-column">
            <span>Pro(Billed Monthly) <i class="fa fa-caret-down"></i></span>
            <a href="#" class="billing">Save 20% with annual billing</a>
          </div>
          <div class="mt-1">
            <sup class="super-price">₹999</sup>
            <span class="super-month">/Month</span>
          </div>
        </div>
        <hr class="mt-0 line">
        <div class="p-3">
          <div class="d-flex justify-content-between mb-2">
            <span>Refferal Bonouses</span>
            <span>-₹100.00</span>
          </div>
          <div class="d-flex justify-content-between">
            <span>Vat <i class="fa fa-clock-o"></i></span>
            <span>-18%</span>
          </div>
        </div>
        <hr class="mt-0 line">
        <div class="p-3 d-flex justify-content-between">
          <div class="d-flex flex-column">
            <span>Today you pay (INR)</span>
            <small>After 30 days ₹899</small>
          </div>
          <span>₹0</span>
        </div>
        <%= form_with(url: new_payment_path, method: :post) do %>
          <div class="p-3">
            <%= submit_tag 'Try it free for 30 days', :class=>"btn btn-primary btn-block" %>
            <div class="text-center">
              <a href= '#' >Have a promo code?</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>