config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, path: '/owners', controllers: { sessions: 'owners/sessions' }
  devise_for :users, path: '/users', controllers: { sessions: 'users/sessions' }

  root 'apartments#index'

  get '/apartments/list', to: 'apartments#list', as: 'list'
  get '/payment', to: 'payments#index', as: 'payment'
  get '/payment/history', to: 'payments#history', as: 'payment_history'
  post '/apartments/payment', to: 'payments#new_payment', as: 'new_payment'
  get '/apartments/my_apartment', to: 'apartments#my_apartment', as: 'my_apartment'
  get '/apartments/:id/owner_details', to: 'apartments#owner_details', as: 'owner_details'
  post '/apartments/:id/owner_details', to: 'payments#reduce_credit', as: 'reduce_credit'
  post '/apartments/:id', to: 'wishlist#add', as: 'add'

  resources :wishlist

  resources :apartments do
    get 'page/:page', action: :index, on: :collection
  end

  match "/404", to: "errors#not_found",via: :all
  match "/500", to: "errors#internal_server_error",via: :all
end

app/models/apartment.rb
class Apartment < ApplicationRecord

  has_many_attached :image
  belongs_to :owner

  validates :apartment_name, presence: :true
  validates :location, presence: :true
  validates :description, presence: :true
  validates :deposit, presence: :true
  validates :rent, presence: :true
  validates :review, presence: :true
  validates :room_size, presence: :true
  validates :tenant, presence: :true
  validates :bedrooms, presence: :true
  validates :bathrooms, presence: :true
  validates :building_age, presence: :true
  validates :balcony, presence: :true
  validates :furnishing_status, presence: :true
  validates :property_type, presence: :true
  validates :posted_date, presence: :true

  validates_numericality_of :bedrooms
  validates_numericality_of :bathrooms
  validates_numericality_of :balcony
  validates_numericality_of :building_age

  scope :filter_by, -> (location) { where("location ilike ?", "%#{location}%")}
  scope :filter_by_search_location, -> (search_location) { where("location ilike ?", "%#{search_location}%")}
  scope :filter_by_owner_id, -> (owner_id) { where owner_id: owner_id }
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

  before_action :find_apartment, only: [:show, :edit, :update, :destroy]

  def index
    @apartments = Apartment.order(:apartment_name).page(params[:page]).per(2)
  end

  def list
    if params[:search].present?
      @apartments = Apartment.filter_by(params[:search].capitalize).filter_by_search_location(params[:search_location].downcase).order(:apartment_name).page(params[:page]).per(2)
    end
  end

  def my_apartment
    if owner_signed_in?
      @apartments = Apartment.filter_by_owner_id(current_owner.id).order(:apartment_name).page(params[:page]).per(2)
    else
      redirect_to owner_session_path
    end
  end

  def owner_details
    if authenticated_user_or_owner?
      @apartment = Apartment.find(params[:id])
      @owner = Owner.find(@apartment.owner_id)
    else
      redirect_to user_session_path
    end
  end

  def show
    if authenticated_user_or_owner?
      @wishlists = ( user_signed_in? ?
        Wishlist.filter_by_apartment_user(current_user.id) :
        Wishlist.filter_by_apartment_owner(current_owner.id)
      ).select(:apartment_id)

      @wishlist_apartment_id = []
      @wishlists.each do |wishlist|
        @wishlist_apartment_id << wishlist.apartment_id
      end
    end
  end

  def new
    if current_owner.credits > 0
      @apartment = Apartment.new
    else
      redirect_to payment_path and return
    end
  end

  def create
    @apartment = Apartment.new(apartment_params)
    @apartment.owner_id = current_owner.id if owner_signed_in?
    reduce_credit()
    if @apartment.save
      redirect_to @apartment
    else
      render :new
    end
  end

  def reduce_credit
    if authenticated_user_or_owner?
      @credits = (user_signed_in?) ? User.find(current_user.id) : Owner.find(current_owner.id)
    else
      redirect_to user_session_path
    end
    @credits.credits -= 1
    if @credits.save
      payment_history("Apartment Created by using 1 Credit","Coin",false)
    end
  end

  def edit
  end

  def update
    if @apartment.update(apartment_params)
      redirect_to @apartment
    else
      render :edit
    end
  end

  def destroy
    @apartment.destroy
    redirect_to root_path
  end

  private

  def find_apartment
    @apartment = Apartment.find(params[:id])
  end

  def apartment_params
    params.require(:apartment).permit(
      :apartment_name,
      :location,
      :description,
      :deposit,
      :rent,
      :review,
      :room_size,
      :bedrooms,
      :tenant,
      :building_age,
      :balcony,
      :furnishing_status,
      :bathrooms,
      :property_type,
      :lift,
      :wifi,
      :ac,
      :fire_safety,
      :security,
      :house_keeping,
      :water_supply,
      :parking,
      :sewage,
      :posted_date,
      :search,
      :search_location,
      :owner => [:id],
      :user => [:id],
      image: []
    )
  end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper

  def edit_profile
    if user_signed_in?
      edit_user_registration_path
    elsif owner_signed_in?
      edit_owner_registration_path
    else
    end
  end

  def authenticated_user_or_owner?
    user_signed_in? or owner_signed_in?
  end

  def image_attached?
    if user_signed_in?
      current_user.profile_image.attached?
    elsif owner_signed_in?
      current_owner.profile_image.attached?
    else
      false
    end
  end

  def profile_image
    if user_signed_in?
      current_user.profile_image
    elsif owner_signed_in?
      current_owner.profile_image
    else
    end
  end

  def current_credits
    if user_signed_in?
      current_user.credits
    elsif owner_signed_in?
      current_owner.credits
    else
    end
  end
end

app/views/apartments/edit.html.erb
<h1>Edit Apartment</h1>
<%= render 'form' %>

app/views/apartments/index.html.erb
<%= render 'layouts/navbar' %>
<div class="wizelite wizelite-fluid ">
  <div class="container text-center my-5 py-5">
    <h1 class="text-white mb-3">Stay Comfort at Anywhere</h1>
    <h1 class="text-white display-1 mb-4">WizElite</h1>
    <div class="mx-auto mb-5" style="width: 100%; max-width: 750px;">
      <div class="booking-form">
        <form action="/apartments/list">
          <%= form_with do |form| %>
            <div class="row">
              <div class="col-3 form-btn">
                <%= form.select :search,[ "Ariyalur",
                                                        "Chennai",
                                                        "Coimbatore",
                                                        "Cuddalore",
                                                        "Dharmapuri",
                                                        "Dindigul",
                                                        "Erode",
                                                        "Kanchipuram",
                                                        "Kanyakumari",
                                                        "Karur",
                                                        "Krishnagiri",
                                                        "Madurai",
                                                        "Nagapattinam",
                                                        "Namakkal",
                                                        "Nilgiris",
                                                        "Perambalur",
                                                        "Pudukkottai",
                                                        "Ramanathapuram",
                                                        "Salem",
                                                        "Sivaganga",
                                                        "Thanjavur",
                                                        "Theni",
                                                        "Thoothukudi",
                                                        "Tiruchirappalli",
                                                        "Tirunelveli",
                                                        "Tiruppur",
                                                        "Tiruvallur",
                                                        "Tiruvannamalai",
                                                        "Tiruvarur",
                                                        "Vellore",
                                                        "Viluppuram",
                                                        "Virudhunagar"
                                                        ] ,{}, {:class=>"form-control"}%>
              </div>
              <div class=" col-9 form-btn">
                <%= form.text_field :search_location, :class=>"form-control", :style=>"padding: 30px 25px;", :placeholder=>"Location" %>
              </div>
            </div>
            <div class="form-btn">
              <%= form.submit 'Search', method: :get, :class=>"submit-btn" %>
            </div>
          <% end %>
        </form>
      </div>
    </div>
  </div>
</div>
</div>

app/views/apartments/list.html.erb
<%= render 'layouts/navbar' %>
<% if @apartments.size == 0 %>
  <div class="text-sm-center mt-100">
    <img src = "https://media.istockphoto.com/vectors/man-is-shrugging-with-a-curious-expression-search-solution-modern-vector-id1159227933?k=20&m=1159227933&s=612x612&w=0&h=tidgxr4nVyq9yyUTLFB9XXayqgFYMg5ZLbj-JUN_xMg=", class="list-image">
    <h1>Oops!! Invalid Page Number</h1>
    <%= link_to 'Go Home', root_path, :class=>"btn btn-danger" %>
  </div>
<% else %>
  <div class="container">
    <br>
    <% if @apartments %>
      <%= paginate @apartments %>
    <% end %>
    <div class="row">
      <div class="col-md-12">
        <div class="people-nearby">
          <% if @apartments %>
            <% @apartments.each do |apartment| %>
              <div class="nearby-user">
                <div class="row">
                  <div class="col-md-3 col-sm-2">
                    <% if apartment.image.attached? %>
                      <a href="<%= apartment.id %>"><%= image_tag apartment.image[1], :class=>"list-image" %></a>
                    <% else %>
                      <a href="<%= apartment.id %>">
                        <img src="https://i0.wp.com/stanzaliving.wpcomstaging.com/wp-content/uploads/2022/06/Benefits-of-booking-accomodation-early.jpg?fit=1000%2C561&ssl=1" class="list-image">
                      </a>
                    <% end %>
                  </div>
                  <div class="col-md-7 col-sm-7">
                    <h5><a href="#" class="profile-link">
                        <%= link_to apartment.bedrooms.to_s+" BHK "+apartment.property_type+" In "+apartment.apartment_name.capitalize+" For Rent In "+apartment.location.capitalize, apartment %>
                      </a></h5>
                    <p><%= apartment.location %></p>
                    <p><span class="badge badge-warning"> <%= apartment.review %> <i class="fa fa-star-o"></i></span></p>
                    <div class="row border">
                      <div class="col-4 mt-2">
                        <p class="text-muted">Sq.ft</p>
                        <h6 class="pb-2"><%= apartment.room_size.to_i %></h6>
                      </div>
                      <div class="col-4 mt-2">
                        <p class="text-muted">Deposit</p>
                        <h6 class="pb-2"><%= apartment.deposit %></h6>
                      </div>
                      <div class="col-4 mt-2">
                        <p class="text-muted">Rent</p>
                        <h6 class="pb-2"><%= apartment.rent %></h6>
                      </div>
                    </div>
                    <div class="row border mt-2">
                      <div class="col-6">
                        <div class="m-2 p-2">
                          <div class="row">
                            <div class="col-2">
                              <i class="fas fa-chair mt-3" aria-hidden="true"></i>
                            </div>
                            <div class="col-10">
                              <h6 class="d-inline mr-1"><%= apartment.furnishing_status.capitalize %></h6>
                              <p class=" mr-1 mb-0 text-muted">Furnishing Status</p>
                            </div>
                          </div>
                        </div>
                        <div class="m-2 p-2">
                          <div class="row">
                            <div class="col-2">
                              <i class="fa fa-users mt-3" aria-hidden="true"></i>
                            </div>
                            <div class="col-10">
                              <h6 class="d-inline mr-1"><%= apartment.tenant.capitalize %></h6>
                              <p class=" mr-1 mb-0 text-muted">Prefered Tenant</p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-6 mt-2">
                        <div class="m-2 p-2">
                          <div class="row">
                            <div class="col-2">
                              <i class="fas fa-building mt-3" aria-hidden="true"></i>
                            </div>
                            <div class="col-10">
                              <h6 class="d-inline mr-1"><%= apartment.bedrooms %> BHK</h6>
                              <p class=" mr-1 mb-0 text-muted">Apartment Type</p>
                            </div>
                          </div>
                        </div>
                        <div class="m-2 p-2">
                          <div class="row">
                            <div class="col-2">
                              <i class="fa fa-home mt-3" aria-hidden="true"></i>
                            </div>
                            <div class="col-10">
                              <h6 class="d-inline mr-1"><%= apartment.property_type.capitalize %></h6>
                              <p class=" mr-1 mb-0 text-muted">Property Type</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-2 col-sm-3">
                    <%= link_to 'View Full Details', apartment, :class=>"btn btn-danger pull-right" %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% if @apartments %>
      <%= paginate @apartments %>
    <% end %>
  </div>
<% end %>

app/views/apartments/new.html.erb
<%= render 'form' %>

app/views/apartments/owner_details.html.erb
<%= render 'layouts/navbar' %>
<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-md-7">
      <div class="card p-3 py-4">
        <div class="text-center">
          <% if @owner.profile_image.attached? %>
            <%= image_tag(@owner.profile_image, width: "100px", :class => "rounded-circle") %>
          <% else %>
            <img src="https://i.imgur.com/bDLhJiP.jpg" width="100" class="rounded-circle">
          <% end %>
        </div>
        <div class="text-center mt-3">
          <span class="bg-secondary p-1 px-4 rounded text-white"> <%= @owner.name %> </span><br/>
          <span>+91 <%= @owner.phonenumber %></span>
          <div class="px-4 mt-1">
            <h5 class="pt-3">
              <%= @apartment.bedrooms.to_s+" BHK "+
                            @apartment.property_type+" In "+
                            @apartment.apartment_name.capitalize+" For Rent In "+
                            @apartment.location.capitalize+" At "+number_to_currency(@apartment.rent, :unit=>'₹').to_s+" Rent" %>
            </h5>
            <p class="fonts"><%= @apartment.description %></p>
          </div>
          <div class="buttons">
            <button class="btn btn-outline-primary px-4">Message</button>
            <button class="btn btn-primary px-4 ms-3">Contact</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/apartments/show.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="card mt-3">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% if @apartment.image.attached? %>
          <div class="carousel-item active">
            <%= image_tag @apartment.image[0], :class=>"d-block w-100" %>
          </div>
          <% @apartment.image.each do |img| %>
            <div class="carousel-item">
              <%= image_tag img, :class=>"d-block w-100" %>
            </div>
          <% end %>
        <% else %>
          <div class="carousel-item active">
            <img src="https://i0.wp.com/stanzaliving.wpcomstaging.com/wp-content/uploads/2022/06/Benefits-of-booking-accomodation-early.jpg?fit=1000%2C561&ssl=1" class="d-block w-100">
          </div>
        <% end %>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row mt-3 justify-content-center border">
      <div class="col-lg-1 border-right">
        <img src="https://raw.githubusercontent.com/vasanthakumar-a/Apartment_Rental_Rails/Reset_App_form_Models/app/assets/images/ze%20logo.png" height="50px" width="50px" class="mt-4">
      </div>
      <div class="col-lg-5 border-right">
        <div class="d-block">
          <h5 class="pt-3"><%= @apartment.bedrooms.to_s+" BHK "+@apartment.property_type+" In "+@apartment.apartment_name.capitalize+" For Rent In "+@apartment.location.capitalize %></h5>
        </div>
        <div class="d-block">
          <p class="text-muted"><%= @apartment.location %></p>
        </div>
      </div>
      <div class="col-lg-2 border-right">
        <div class="d-block">
          <h6 class="pt-3"><%= @apartment.room_size.to_i %></h6>
        </div>
        <div class="d-block">
          <p class="text-muted">Sq.ft</p>
        </div>
      </div>
      <div class="col-lg-2 border-right">
        <div class="d-block">
          <h6 class="pt-3"><%= number_to_currency(@apartment.deposit, :unit=> '₹ ') %></h6>
        </div>
        <div class="d-block">
          <p class="text-muted">Deposit</p>
        </div>
      </div>
      <div class="col-lg-2">
        <div class="d-block">
          <h6 class="pt-3"><%= number_to_currency(@apartment.rent, :unit => '₹ ') %>/month</h6>
        </div>
        <div class="d-block">
          <p class="text-muted">Rent</p>
        </div>
      </div>
    </div>
    <div class="row mt-4 justify-content-center">
      <div class="col-lg-8 border">
        <div class="mt-3 text-start mb-1-6 wow fadeIn">
          <h4 class="mb-0">Overview</h4>
        </div>
        <div class="row">
          <div class="col-6 justify-content">
            <div class="ps-lg-1-6 ps-xl-5">
              <div class="mb-5 wow fadeIn">
                <div class="d-block m-4 pr-1">
                  <i class="fa fa-home" aria-hidden="true"></i>
                  <div class="d-inline ml-2">Furnishing Status</div>
                </div>
                <div class="d-block m-4 pr-1">
                  <i class="fa fa-tint" aria-hidden="true"></i>
                  <div class="d-inline ml-2">Water Supply</div>
                </div>
                <div class="d-block m-4 pr-1">
                  <i class="fa fa-bath" aria-hidden="true"></i>
                  <div class="d-inline ml-2">Bathrooms </div>
                </div>
                <div class="d-block m-4 pr-1">
                  <i class="fa fa-bed" aria-hidden="true"></i>
                  <div class="d-inline ml-2">Bedrooms </div>
                </div>
                <div class="d-block m-4 pr-1">
                  <i class="fa fa-users" aria-hidden="true"></i>
                  <div class="d-inline ml-2">Prefered Tenant </div>
                </div>
                <div class="d-block m-4 pr-1">
                  <i class="fa fa-building" aria-hidden="true"></i>
                  <div class="d-inline ml-2">Property Type </div>
                </div>
                <div class="d-block m-4 pr-1">
                  <i class="fa fa-calendar" aria-hidden="true"></i>
                  <div class="d-inline ml-2">Posted Date </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-6">
            <div class="ps-lg-1-6 ps-xl-5">
              <div class="mb-5 wow fadeIn">
                <div class="d-block m-4 pr-1">
                  <div class="d-inline ml-2"><%= @apartment.furnishing_status.capitalize %></div>
                </div>
                <div class="d-block m-4 pr-1">
                  <div class="d-inline ml-2"><% if @apartment.water_supply %>Yes<%else%>No<%end%></div>
                </div>
                <div class="d-block m-4 pr-1">
                  <div class="d-inline ml-2"><%= @apartment.bathrooms %></div>
                </div>
                <div class="d-block m-4 pr-1">
                  <div class="d-inline ml-2"><%= @apartment.bedrooms %></div>
                </div>
                <div class="d-block m-4 pr-1">
                  <div class="d-inline ml-2"><%= @apartment.tenant.capitalize %></div>
                </div>
                <div class="d-block m-4 pr-1">
                  <div class="d-inline ml-2"><%= @apartment.property_type.capitalize %></div>
                </div>
                <div class="d-block m-4 pr-1">
                  <div class="d-inline ml-2"><%= @apartment.posted_date %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-7 col-lg-4 mb-5 mb-lg-0 wow fadeIn">
        <%# Transactions Box %>
        <div class="card mt-5 border-1 shadow-lg p-3 mb-5 bg-black rounded">
          <div class="card-body">
            <% if owner_signed_in? and current_owner.id == @apartment.owner_id %>
              <%= link_to "Edit Apartment Details", edit_apartment_path, :class => 'btn btn-primary mt-2 ml-sm-0' %>
              <%= link_to 'Delete Apartment', apartment_path, method: :delete, :class => 'btn btn-danger m-2 ml-sm-0' %>
            <% elsif user_signed_in? or owner_signed_in? %>
              <%= link_to 'Get Owner Details', reduce_credit_path, method: :post, :class => 'btn btn-danger m-2 ml-sm-0' %>
              <% if @wishlist_apartment_id.to_a.include?(params[:id].to_i) %>
                <%= link_to wishlist_index_path, :class => 'btn btn-danger m-2 ml-sm-0' do %>
                  <i class="fa fa-check-circle"></i> Already Favourite
                <% end %>
              <% else %>
                <%= link_to add_path, method: :post, :class => 'btn btn-danger m-2 ml-sm-0' do %>
                  <i class="fa fa-star"></i> Add to Favourite
                <% end %>
              <% end %>
            <% else %>
              <%= link_to 'Get Owner Details', new_user_session_path, :class => 'btn btn-danger m-2 ml-sm-0' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row mt-3 justify-content-left">
      <div class="col-lg-8 border">
        <div class="mt-3 text-start mb-1-6 wow fadeIn">
          <h4 class="mb-0">Description</h4>
        </div>
        <div class="row">
          <div class="col-12 justify-content">
            <div class="ps-lg-1-6 ps-xl-5">
              <div class="mb-5 wow fadeIn">
                <div class="d-block m-4 pr-1">
                  <p class="card-text"><%= @apartment.description %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row mt-3 mb-5 justify-content-left">
      <div class="col-lg-8 border">
        <div class="mt-3 text-start mb-1-6 wow fadeIn">
          <h4 class="mb-0">Aminities</h4>
        </div>
        <div class="row m-3">
          <div class="col-12 justify-content">
            <div class="d-inline m-4 pr-1">
              <% if @apartment.lift %>
                <i class="fa-solid fa-elevator ml-2" aria-hidden="true"></i>
                <div class="d-inline ml-2">Lift</div>
              <% end %>
            </div>
            <div class="d-inline m-4 pr-1">
              <% if @apartment.wifi %>
                <i class="fa fa-wifi ml-2" aria-hidden="true"></i>
                <div class="d-inline ml-2">Wifi</div>
              <% end %>
            </div>
            <div class="d-inline m-4 pr-1">
              <% if @apartment.ac %>
                <i class="fas fa-digital-tachograph ml-2" aria-hidden="true"></i>
                <div class="d-inline ml-2">AC</div>
              <% end %>
            </div>
            <div class="d-inline m-4 pr-1">
              <% if @apartment.fire_safety %>
                <i class="fa fa-fire-extinguisher ml-2" aria-hidden="true"></i>
                <div class="d-inline ml-2">Fire Safety</div>
              <% end %>
            </div>
            <div class="d-inline m-4 pr-1">
              <% if @apartment.security %>
                <i class="fas fa-user-shield ml-2" aria-hidden="true"></i>
                <div class="d-inline ml-2">Security</div>
              <% end %>
            </div>
            <div class="d-inline m-4 pr-1">
              <% if @apartment.house_keeping %>
                <i class="fas fa-broom ml-2" aria-hidden="true"></i>
                <div class="d-inline ml-2">House Keeping</div>
              <% end %>
            </div>
            <div class="d-inline m-4 pr-1">
              <% if @apartment.parking %>
                <i class="fas fa-parking ml-2" aria-hidden="true"></i>
                <div class="d-inline ml-2">Parking</div>
              <% end %>
            </div>
            <div class="d-inline m-4 pr-1">
              <% if @apartment.sewage %>
                <i class="fa fa-trash-o ml-2" aria-hidden="true"></i>
                <div class="d-inline ml-2">Sewage</div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/apartments/wishlist.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <br>
  <div class="row">
    <div class="col-md-12">
      <div class="people-nearby">
        <% if @apartments %>
          <% @apartments.each do |apartment| %>
            <div class="nearby-user">
              <div class="row">
                <div class="col-md-3 col-sm-2">
                  <% if apartment.image.attached? %>
                    <a href="<%= apartment.id %>"><%= image_tag apartment.image[1], :class=>"list-image" %></a>
                  <% else %>
                    <a href="<%= apartment.id %>">
                      <img src="https://i0.wp.com/stanzaliving.wpcomstaging.com/wp-content/uploads/2022/06/Benefits-of-booking-accomodation-early.jpg?fit=1000%2C561&ssl=1" class="list-image">
                    </a>
                  <% end %>
                </div>
                <div class="col-md-7 col-sm-7">
                  <h5><a href="#" class="profile-link">
                      <%= link_to apartment.bedrooms.to_s+" BHK "+apartment.property_type+" In "+apartment.apartment_name.capitalize+" For Rent In "+apartment.location.capitalize, apartment %>
                    </a></h5>
                  <p><%= apartment.location %></p>
                  <p><span class="badge badge-warning"> <%= apartment.review %> <i class="fa fa-star-o"></i></span></p>
                  <div class="row border">
                    <div class="col-4 mt-2">
                      <p class="text-muted">Sq.ft</p>
                      <h6 class="pb-2"><%= apartment.room_size.to_i %></h6>
                    </div>
                    <div class="col-4 mt-2">
                      <p class="text-muted">Deposit</p>
                      <h6 class="pb-2"><%= apartment.deposit %></h6>
                    </div>
                    <div class="col-4 mt-2">
                      <p class="text-muted">Rent</p>
                      <h6 class="pb-2"><%= apartment.rent %></h6>
                    </div>
                  </div>
                  <div class="row border mt-2">
                    <div class="col-6">
                      <div class="m-2 p-2">
                        <div class="row">
                          <div class="col-2">
                            <i class="fas fa-chair mt-3" aria-hidden="true"></i>
                          </div>
                          <div class="col-10">
                            <h6 class="d-inline mr-1"><%= apartment.furnishing_status.capitalize %></h6>
                            <p class=" mr-1 mb-0 text-muted">Furnishing Status</p>
                          </div>
                        </div>
                      </div>
                      <div class="m-2 p-2">
                        <div class="row">
                          <div class="col-2">
                            <i class="fa fa-users mt-3" aria-hidden="true"></i>
                          </div>
                          <div class="col-10">
                            <h6 class="d-inline mr-1"><%= apartment.tenant.capitalize %></h6>
                            <p class=" mr-1 mb-0 text-muted">Prefered Tenant</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-6 mt-2">
                      <div class="m-2 p-2">
                        <div class="row">
                          <div class="col-2">
                            <i class="fas fa-building mt-3" aria-hidden="true"></i>
                          </div>
                          <div class="col-10">
                            <h6 class="d-inline mr-1"><%= apartment.bedrooms %> BHK</h6>
                            <p class=" mr-1 mb-0 text-muted">Apartment Type</p>
                          </div>
                        </div>
                      </div>
                      <div class="m-2 p-2">
                        <div class="row">
                          <div class="col-2">
                            <i class="fa fa-home mt-3" aria-hidden="true"></i>
                          </div>
                          <div class="col-10">
                            <h6 class="d-inline mr-1"><%= apartment.property_type.capitalize %></h6>
                            <p class=" mr-1 mb-0 text-muted">Property Type</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-2 col-sm-3">
                  <%= link_to 'View Full Details', apartment, :class=>"btn btn-danger pull-right" %>
                  <%= link_to 'Remove Favourite', wishlist_destroy_path, :class => 'btn btn-danger pull-right' %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>