config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, path: '/owners', controllers: { sessions: 'owners/sessions' }
  devise_for :users, path: '/users', controllers: { sessions: 'users/sessions' }

  root 'apartments#index'

  get '/apartments/list', to: 'apartments#list', as: 'list'
  get '/payment', to: 'payments#index', as: 'payment'
  get '/payment/history', to: 'payments#history', as: 'payment_history'
  post '/apartments/payment', to: 'payments#new_payment', as: 'new_payment'
  get '/apartments/my_apartment', to: 'apartments#my_apartment', as: 'my_apartment'
  get '/apartments/:id/owner_details', to: 'apartments#owner_details', as: 'owner_details'
  post '/apartments/:id/owner_details', to: 'payments#reduce_credit', as: 'reduce_credit'
  post '/apartments/:id', to: 'wishlist#add', as: 'add'

  resources :wishlist

  resources :apartments do
    get 'page/:page', action: :index, on: :collection
  end

  match "/404", to: "errors#not_found",via: :all
  match "/500", to: "errors#internal_server_error",via: :all
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="/">
        <%= image_tag 'wizelite.png', :class=>"logo" %>
      </a>
      <% if owner_signed_in? %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "My Apartments", my_apartment_path, :class => 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "New Apartment", new_apartment_path, :class => 'nav-link text-dark' %>
        </li>
      </ul>
      <% end %>
    </div>

    <div class="d-flex align-items-center">
      <% if authenticated_user_or_owner?%>
      <%= link_to wishlist_index_path, :class => 'text-reset nav-link' do %>
        <i class="fa fa-bookmark text-danger"></i>
      <% end %>
      <%= link_to payment_path, :class => 'nav-link' do %>
        <i class="fas fa-coins text-dark"></i>
        <span class="badge bg-danger text-light"><%=current_credits.to_i%></span>
      <% end %>
      <% else %>
            <%= link_to 'Owner Login', new_owner_session_path, :class => 'nav-link text-dark' %>
            <%= link_to 'Signup', new_user_registration_path, :class => 'nav-link text-dark' %>
            <%= link_to 'Login', new_user_session_path, :class => 'nav-link text-dark' %>
      <%end%>

      <div class="dropdown">
        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if image_attached? %>
          <%= image_tag profile_image, class: "rounded-circle", height: "30" %>
          <% else %>
          <img
            src="https://cdn-icons-png.flaticon.com/512/149/149071.png"
            class="rounded-circle"
            height="25"
          />
          <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if authenticated_user_or_owner? %>
            <%= link_to 'My profile', edit_profile, :class => 'dropdown-item' %>
            <%= link_to 'Settings', edit_profile, :class => 'dropdown-item' %>
          <%= link_to "Logout", destroy_owner_session_path, method: :delete, :class => 'dropdown-item' %>
          <% else %>
            <%= link_to 'Owner Login', new_owner_session_path, :class => 'dropdown-item' %>
            <%= link_to 'Signup', new_user_registration_path, :class => 'dropdown-item' %>
            <%= link_to 'Login', new_user_session_path, :class => 'dropdown-item' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApartmentRentalRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "ze logo.png"%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <%# <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.css" rel="stylesheet"/> %>
    <%# <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.js"></script> %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a071518e2f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/boxicons/2.1.0/css/boxicons.min.css" integrity="sha512-pVCM5+SN2+qwj36KonHToF2p1oIvoU3bsqxphdOIWMYmgr4ZqD3t5DjKvvetKhXGc/ZG5REYTT6ltKfExEei/Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Web/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <%# <p class="notice"><%= notice %><%# </p>
    <%# <p class="alert"><%= alert %><%# </p> %>
    <%= yield %>
  </body>
</html>